### ISSUE TITLE
Add VERSION file to Docker images

### ISSUE THREAD

**Issue by zerok** [grafana/grafana-build#145]
All packages contain (or install) a VERSION file except for the Docker images. We will probably have to again adapt the Dockerfile stored in grafana/grafana for this. Since this file is not available in the repository itself, though, we might need to inject its content as an `ARG` to Docker, though.

This is a follow-up to #90

**Comment by kminehart** [comment]
Our docker builds use the .tar.gz as input (even though the dockerfile is in the Grafana repo). We could just get it from that.

**Comment by zerok** [comment]
I wanted to keep the whole thing compatible with the `make build-docker-full` workflow. Not sure how relevant that is at this point.
