### ISSUE TITLE
Custom builds are created in the cloud

### ISSUE THREAD

**Issue by summerwollin** [grafana/grafana-build#251]
Problem: [Custom builds ](https://backstage.grafana-ops.net/docs/default/component/grafana-delivery/runbooks/custom-builds/) and [Booking builds](https://backstage.grafana-ops.net/docs/default/component/grafana-delivery/runbooks/custom-booking/) currently require engineers to check out branches and run scripts on their local machines. This requires every engineer in the guild to have to install and set up a lot of dependencies such as grafana-build, docker, push permissions for GCP etc. The build job also takes a long time to complete and often fails on some machines for reasons unique to that engineer's personal device and set up. This also makes hand off difficult as some artifacts only exist on one person's machine until it is pushed.

Goal: Instead of running scripts locally we should build automation tooling that can be run in the cloud. Whether this is built with Drone or some other tool is TBD. This will eliminate the need for any local set up and thusly any bugs related to individual device set ups. This will also enable non-release engineers to be able to create custom builds themselves. This is currently a need specifically with the [Booking releases](https://backstage.grafana-ops.net/docs/default/component/grafana-delivery/runbooks/custom-booking/) as a non-release guild squad is going to take ownership of creating the Booking releases moving forward.

Requirements:

- The new tooling has no local steps
- A UI exists that is easy to use
- Service account exists for the automation so that it has the correct permissions
- Automation creates the built Grafana images and uploads them to GCP
- Automation can build RPM packages
- Documentation is updated
- Runbooks are updated

**Comment by kminehart** [comment]
Solution: We will need to add a new promotion pipeline in Grafana's drone.yml that will run `grafana-build artifacts -a ...`.

It needs to be configurable with:

* `grafana-ref`
* `enterprise-ref`
* `artifacts` (like `rpm:linux/amd64:grafana`)
* `version`
