### ISSUE TITLE
Add a Dockerfile and start automatically publishing the docker image

### ISSUE THREAD

**Issue by kminehart** [grafana/grafana-build#47]
We should have the docker image automatically published on all branch pushes and tags.

**Comment by zerok** [comment]
Generting container images (as files) is rather easy but pushing those to GCR will be a bit more complicated on Drone as plugins/gcr does not take a ready-made image file as input :(

**Comment by kminehart** [comment]
I'm fine with not using the plugin too. The plugin is obviously nice because it limits PRs ability to mess around with steps that have the docker socket mounted... :thinking:
