### ISSUE TITLE
Naming: Packages

### ISSUE THREAD

**Issue by zerok** [grafana/grafana-build#83]
Since we are using the tarball as some kind of generic bundle that can then be transformed into a deb, rpm, or exe, I think it would be better to update the naming a bit:

- `bundle` creates the tarball
- `package --format=rpm` would create a RPM file
- `package --format=deb` would create a DEB file
- `package --format=msi` would create an MSI installer

Right now, we have a lot of subcommands that do pretty much the same thing except when it comes to the output format.

WDYT?

**Comment by kminehart** [comment]
Right now the `--destination` argument is a directory, and the file name is decided by the subcommand but generally uses the same file name as the input tar.gz, but with a different extension.

**Comment by zerok** [comment]
Ah, good point
