### ISSUE TITLE
Add LICENSE to docker images

### ISSUE THREAD

**Issue by guicaulada** [grafana/grafana-build#90]
The LICENSE is usually present on `/usr/share/grafana` but on Docker packages they are not.
```
/usr/share/grafana $ ls
bin     conf    public
```

**Comment by zerok** [comment]
Neither is the VERSION file part of the Docker images and hasn't been also in the old way. We might just tackle both at the same time 🙂

**Comment by zerok** [comment]
I'll create a follow-up ticket for the VERSION file.
